openapi: "3.0.0"
info:
  title: Nutritionix API
  version: "2.0"
  description: "Signup for a Nutritionix API developer account at developer.nutritionix.com. When logged into the Nutritionix developer console, get your APP ID and APP Key at this page: https://developer.nutritionix.com/admin/access_details. Required HEADERS when accessing Nutritionix V2 API endpoints: x-app-id, x-app-key, x-remote-user-id. Please note, when authenticating with the API, you must send the x-app-id and x-app-key params as headers, and not as query string parameters."
servers:
  - url: "https://trackapi.nutritionix.com"
paths:
  /v2/natural/nutrients:
    post:
      summary: Get detailed nutrient breakdown of any natural language text.
      operationId: postNutrients
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: Natural language text
              required:
                - query
      responses:
        "200":
          description: Nutrient breakdown
          content:
            application/json:
              schema:
                type: object
      security:
        - APIKeyHeader: []
  
  /v2/natural/exercise:
    post:
      summary: Estimate calories burned for various exercises using natural language.
      operationId: postExercise
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: Natural language text
                age:
                  type: integer
                gender:
                  type: string
                weight_kg:
                  type: number
              required:
                - query
      responses:
        "200":
          description: Calories burned estimate
          content:
            application/json:
              schema:
                type: object
      security:
        - APIKeyHeader: []
components:
  securitySchemes:
    APIKeyHeader:
      type: apiKey
      in: header
      name: x-app-id
    APIKeyHeader2:
      type: apiKey
      in: header
      name: x-app-key
    APIKeyHeader3:
      type: apiKey
      in: header
      name: x-remote-user-id
security:
  - APIKeyHeader: []
    APIKeyHeader2: []
    APIKeyHeader3: []
